authors:
  ryan:
    name: Ryan McLaughlin
    description: Systems Architect
    email: ryan@mclaughlin.engineering
    url: https://mclaughlin.engineering
    avatar: https://gravatar.com/avatar/14b92be7814e53b8d1451a9863941b9ab440d3ca6a3759a13345ea9332782ea8?d=mp